### ISSUE TITLE
Issue with long words hastebin 

### ISSUE THREAD

**Issue by PaawanTono** [lap00zza/LapzbotIssueTracker#2]
http://prntscr.com/asojhn  that *Click is joined with link so it's broken. and also can u make it embed little of text be4 the hastbin link. Sometimes what we need can be in those starting lines so no need to actually open the link. :)

**Comment by lap00zza** [comment]
This is fixed. Will be pushed with the next update. Also hastebin links don't support embeds at the moment. I will make the bot add a little snippet along with the link. This fixes it.
